### ISSUE TITLE
Add a feed?

### ISSUE THREAD

**Issue by tfausak** [jxv/jxv.github.io#3]
Hi! I am the editor of [Haskell Weekly](https://haskellweekly.news). I would like to be notified when you write a new post, but as far as I can tell your blog does not have a feed. Would you mind adding an Atom or RSS feed? Thanks!

**Comment by jxv** [comment]
Hey! Yes, I want to add a feed. It's on my todo list ( https://github.com/jxv/stagen/issues/1 ). I'll ping you when it's added.

**Comment by tfausak** [comment]
Great, thanks!

**Comment by jxv** [comment]
@tfausak Added three feeds: atom, rss, and json feed, which uses your library. Double thanks!

**Comment by tfausak** [comment]
Fantastic, thank you!

**Comment by turanct** [comment]
superb! i was following using the feed of this repo ;-) i now subscribed on the RSS feed of the blog thanks a lot!
